prometheus_web_external_url: http://127.0.0.1/prometheus

prometheus_global:
  scrape_interval: 30s

prometheus_scrape_jobs:
  - job_name: "node"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "178.128.24.42:9100"
  - job_name: "mariadb"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "localhost:9104"
