- hosts: nfs
  vars:
    nfs_exports:
      - "/home/public *(rw,sync,no_root_squash)"
    # Only RedHat/CentOS/Fedora
    # nfs_rpcbind_state: started
    # nfs_rpcbind_enabled: true
  roles:
    - { role: geerlingguy.nfs }
