---
- hosts: masters
  tasks:
    - name: initialize the cluster
      become: yes
      shell: kubeadm init --pod-network-cidr={{ ip_range }} --apiserver-advertise-address={{ master_ip }} >> cluster_initialized.txt
      args:
        chdir: /home/csag/
        creates: cluster_initialized.txt

    - name: create .kube directory
      file:
        path: /home/csag/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/csag/.kube/config
        remote_src: yes
        owner: csag

    - name: install Pod network
      become: true
      become_user: csag
      shell: kubectl apply -f {{ network_plugin_service }} >> pod_network_setup.txt
      args:
        chdir: /home/csag/
        creates: pod_network_setup.txt

    - name: install kubernetes dashboard
      become: true
      become_user: csag
      shell: kubectl apply -f {{ dashboard_service }}

    - name: create admin user
      become: true
      become_user: csag
      shell: kubectl apply -f k8s/k8s-user.yml

    - name: bind role
      become: true
      become_user: csag
      shell: kubectl apply -f k8s/k8s-role.yml
    
    - name: get token
      become: true
      become_user: csag
      shell: kubectl -n kubernetes-dashboard describe secret $(kubectl -n kubernetes-dashboard get secret | grep admin-user | awk '{print $1}')